### PR TITLE
#150398695 Configure Eslint -chore

### PR DESCRIPTION
**Pull request by bumsyalao**
#### What does this PR do?
Configures eslint 
#### Description of Task to be completed?
-Install eslint, install eslint airbnb-base, install eslint airbnb-base plugin
#### How should this be manually tested?
Tested by running the command 'eslint app' on terminal
#### Any background context you want to provide?
 Eslint has been configured
#### Screenshots (if appropriate)
screen shot 2017-08-23 at 12 31 37 pm

#### Questions: none

### CODE REVIEW

**Comment by Kenec** [comment]
I think you should add this to the eslint file
"max-len": [1, 80, 2]

**Comment by bumsyalao** [comment]
@Kenec This has been implemented. Thanks

**Review by VanPaitin — CHANGES_REQUESTED** [review]
Try to rebase and then resolve the merge conflicts. If you have problems rebasing, you could pair with @jattoabdul

**Comment by VanPaitin** [comment]
The changes are already in staging

**Pull request closed without merging**
